WIP: Support for purescript v0.14
f-o-a-m/purescript-web3-generator pull request #65
Opened 2021-07-09 18:12 UTC by kejace

2021-07-09 19:46 UTC, kejace commented
I have tested this with `chanterelle-halogen-template` and it works in the browser.

2021-07-12 15:38 UTC, blinky3713 requested changes

2021-07-12 15:38 UTC, blinky3713 commented on src/Data/Generator.purs
> -toPayload isWhereClause typeName args = do
if toPayload can be redefined without taking this argument, we should do that

2021-07-12 15:38 UTC, blinky3713 commented on src/Data/Generator.purs
> +    whereHelper _ pre _ ret = do
are these arguments being used anywhere? If not we should remove them entirely

2021-07-12 15:38 UTC, blinky3713 commented on src/Data/Generator.purs
> +funToTypeDecl fun@(SolidityFunction f) _ = do
Can we remove the `CodeOptions` arg and eveyrthing still work?

2021-07-13 18:23 UTC, blinky3713 approved these changes

2021-07-14 16:14 UTC, merged